services:
  # --------------------------------------------
  # MOSQUITTO -----------------------------------
  # --------------------------------------------
  broker:
    env_file:
      - .env
    container_name: mosquitto-container
    hostname: mosquittoName
    image: eclipse-mosquitto
    ports:
      - "${MOSQUITTO_PORT}:1883"
    networks:
      - mqtt
    volumes:
      - ./mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro

  # --------------------------------------------
  # sensors -----------------------------------
  # --------------------------------------------
  sensors:
    container_name: sensContNet
    hostname: sensHost
    build: ./sensors/
    volumes:
      - ./simulated_env:/simulated_env
    depends_on:
      - broker
    networks:
      - mqtt

  # --------------------------------------------
  # actuators -----------------------------------
  # --------------------------------------------
#  actuators:
#    container_name: actCont
#    hostname: actHost
#    build: ./actuators/
#    volumes:
#      - ./simulated_env:/simulated_env


#  analysis:
#    container_name: analysisCont
#    hostname: analysisHost
#    build: ./analysis/
#
#  planner:
#    container_name: plannerCont
#    hostname: plannerHost
#    build: ./planner/

networks:
  mqtt:
    driver: bridge

volumes:
  mosquitto_data:
  simulated_env:
