apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    jsonData:
      httpMode: POST
      organization: network-monitoring   # usato da InfluxDB 2.x
      defaultBucket: network-metrics    # bucket per i dati
      tlsAuth: false
      version: Flux
    secureJsonData:
      token: my-super-secret-token
